### ISSUE TITLE
Approvazione Project Plan

### ISSUE THREAD

**Issue by zanottipaolo** [zanottipaolo/IS-Project#10]
Buongiorno professore,
Con questo issue chiediamo l'approvazione del nostro [Project Plan](https://github.com/zanottipaolo/IS-Project/blob/main/docs/project-plan.md).

Inoltre volevamo chiederle, i diagrammi utilizzati sono sufficienti? O bisogna farne almeno un paio per tipo? Perché per alcuni non siamo riusciti a rappresentare tutte le funzionalità richieste nella Check-List su Team.

Grazie!

**Comment by garganti** [comment]
molto bene. Project plan approvato.

**Comment by garganti** [comment]
Riguardo ai diagrammi seguite la check list - non ho capito cosa non riuscite a rappresentare con i diagrammi.
